apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-dockerless-runner
  namespace: forgejo
  annotations:
    container.apparmor.security.beta.kubernetes.io/runner: unconfined
spec:
  serviceName: forgejo-dockerless-runner
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-dockerless-runner
  template:
    metadata:
      labels:
        app: forgejo-dockerless-runner
    spec:
      restartPolicy: Always
      initContainers:
      - name: format-podman-graph
        image: alpine:3.20
        command: ["sh", "-c", "apk add --no-cache e2fsprogs util-linux && if ! blkid /dev/rbdblock >/dev/null 2>&1; then mkfs.ext4 -F /dev/rbdblock; fi"]
        securityContext:
          privileged: true
        volumeDevices:
        - name: podman-graph
          devicePath: /dev/rbdblock
      containers:
        - name: rbd-mounter
          image: alpine:3.20
          securityContext:
            privileged: true
          command:
          - sh
          - -c
          - |
            apk add --no-cache util-linux
            mkdir -p /mnt/src /mnt/dst
            mount /dev/rbdblock /mnt/src
            mount --bind /mnt/src /mnt/dst
            echo "Mounted /dev/rbdblock -> /mnt/dst"
            tail -f /dev/null
          volumeDevices:
          - name: podman-graph
            devicePath: /dev/rbdblock
          volumeMounts:
          - name: podman-graph-mnt
            mountPath: /mnt/dst
            mountPropagation: Bidirectional
        - name: runner
          image: "registry.spbnix.com/dockerhub-cache/gitinsky/dockerless-forgejo-runner:49c909e"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            readOnlyRootFilesystem: false
            capabilities:
              add: ["SYS_ADMIN"]
            seccompProfile:
              type: Unconfined
          envFrom:
            - secretRef:
                name: forgejo-token
          env:
            - name: FORGEJO_URL
              value: "http://forgejo-http.forgejo.svc.cluster.local:3000"
          volumeMounts:
            - name: runner-data
              mountPath: /home/forgejo/data
            - name: tmp-volume
              mountPath: /tmp
            - name: root-cache
              mountPath: /root/.cache
            - name: local-share
              mountPath: /home/forgejo/.local
            - name: podman-graph-mnt
              mountPath: /var/lib/containers
              mountPropagation: HostToContainer
            - name: podman-graph-mnt
              mountPath: /var/run/containers
              subPath: run
              mountPropagation: HostToContainer
      volumes:
      - name: root-cache
        persistentVolumeClaim:
          claimName: root-cache
      - name: podman-graph
        persistentVolumeClaim:
          claimName: podman-graph-forgejo-dockerless-runner-0
      - name: podman-run
        emptyDir:
          medium: Memory
      - name: podman-graph-mnt
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: runner-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
  - metadata:
      name: local-share
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
  - metadata:
      name: tmp-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
  - metadata:
      name: podman-graph
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: ceph-block-3
      resources:
        requests:
          storage: 50Gi
      volumeMode: Block
