apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-dockerless-runner
  namespace: forgejo
  annotations:
    container.apparmor.security.beta.kubernetes.io/runner: unconfined
spec:
  serviceName: forgejo-dockerless-runner
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-dockerless-runner
  template:
    metadata:
      labels:
        app: forgejo-dockerless-runner
    spec:
      restartPolicy: Always
      containers:
        - name: runner
          image: "registry.spbnix.com/dockerhub-cache/gitinsky/dockerless-forgejo-runner:e80107a"
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
            runAsUser: 0
            readOnlyRootFilesystem: false
            capabilities:
              add: ["SYS_ADMIN"]
            seccompProfile:
              type: Unconfined
          envFrom:
            - secretRef:
                name: forgejo-token
          env:
            - name: FORGEJO_URL
              value: "http://forgejo-http.forgejo.svc.cluster.local:3000"
          volumeMounts:
            - name: runner-data
              mountPath: /home/forgejo/data
            - name: tmp-volume
              mountPath: /tmp
            - name: root-cache
              mountPath: /root/.cache
            - name: local-share
              mountPath: /home/forgejo/.local
            - name: podman-graph
              mountPath: /var/lib/containers
            - name: podman-run
              mountPath: /var/run/containers
      volumes:
      - name: root-cache
        persistentVolumeClaim:
          claimName: root-cache
      - name: podman-graph
        hostPath:
          path: /var/lib/forgejo-runner/containers
          type: DirectoryOrCreate
      - name: podman-run
        hostPath:
          path: /var/run/forgejo-runner/containers
          type: DirectoryOrCreate
  volumeClaimTemplates:
  - metadata:
      name: runner-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
  - metadata:
      name: local-share
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
  - metadata:
      name: tmp-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
