apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo-dockerless-runner
  namespace: forgejo
spec:
  serviceName: forgejo-dockerless-runner
  replicas: 1
  selector:
    matchLabels:
      app: forgejo-dockerless-runner
  template:
    metadata:
      labels:
        app: forgejo-dockerless-runner
    spec:
      restartPolicy: Always
      containers:
        - name: runner
          image: "gitinsky/dockerless-forgejo-runner:ced6468"
          securityContext:
            privileged: true
            runAsUser: 0
            readOnlyRootFilesystem: false
          envFrom:
            - secretRef:
                name: forgejo-token
          env:
            - name: FORGEJO_URL
              value: "http://forgejo-http.forgejo.svc.cluster.local:3000"
          volumeMounts:
            - name: runner-data
              mountPath: /home/forgejo/data
            - name: tmp-volume
              mountPath: /tmp
            - name: root-cache
              mountPath: /root/.cache
            - name: local-share
              mountPath: /home/forgejo/.local
      volumes:
      - name: root-cache
        persistentVolumeClaim:
          claimName: root-cache
  volumeClaimTemplates:
  - metadata:
      name: runner-data
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
  - metadata:
      name: local-share
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
  - metadata:
      name: tmp-volume
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 3Gi
      storageClassName: ceph-block-3-uncompressed
