apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aptly
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: aptly
  releaseName: aptly
  chart:
    spec:
      chart: aptly
      version: "0.4.0"
      sourceRef:
        kind: HelmRepository
        name: g0dscookie
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    config:
      gpg:
        disableSign: false
        disableVerify: false
        realname: "Alex Chistyakov"
        email: alexclear@gmail.com

    aptly:
      podSecurityContext:
        fsGroup: 1000
      image:
        tag: "1.6.1"
      ingress:
        enabled: true
        hostname: aptly-pve1.spbnix.local
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: local-root-ca-issuer
        path: /api/
        tls:
          - hosts:
            - aptly-pve1.spbnix.local
            secretName: aptly-pve1-tls-secret

    persistence:
      accessMode: ReadWriteOnce
      storageClassName: "ceph-block-3"
      size: 1Gi

    nginx:
      ingress:
        enabled: true
        hostname: aptly-pve1.spbnix.local
        className: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: local-root-ca-issuer
        paths:
          - path: /
        tls:
          - hosts:
            - aptly-pve1.spbnix.local
            secretName: aptly-pve1-tls-secret
