apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: aptly
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: aptly
  releaseName: aptly
  chart:
    spec:
      chart: aptly
      version: "0.4.0"
      sourceRef:
        kind: HelmRepository
        name: g0dscookie
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    config:
      gpg:
        disableSign: false
        disableVerify: false
        realname: "Alex Chistyakov"
        email: alexclear@gmail.com

    aptly:
      image:
        tag: "1.6.1"
      ingress:
        enabled: true
        hostname: aptly-pve1.spbnix.local
        className: "nginx"
        annotations: {}
          # kubernetes.io/ingress.class: nginx
          # kubernetes.io/tls-acme: "true"
        path: /api/
        tls: []

    persistence:
      accessMode: ReadWriteOnce
      storageClassName: "ceph-block-3"
      size: 1Gi
