apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: root-cache
  namespace: forgejo
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 120Gi
  storageClassName: ceph-block-3
  volumeMode: Filesystem
