apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: graylog
  namespace: graylog
spec:
  interval: 5m
  targetNamespace: graylog
  releaseName: graylog
  chart:
    spec:
      chart: graylog
      version: "3.0.5"
      sourceRef:
        kind: HelmRepository
        name: kong-z
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    tags:
      install-opensearch: false
      install-mongodb: false

    graylog:
      persistence:
        enabled: true
        size: "2Gi"
        storageClass: "ceph-block-3"

      heapSize: "1g"
      opensearch:
        hosts: "http://opensearch-cluster-master-headless.graylog.svc.cluster.local:9200"

      mongodb:
        uriSecretName: "mongodb-graylog-graylog"
        uriSecretKey: "connectionString.standard"
      input:
        udp:
          service:
            type: LoadBalancer
            ports:
              - name: syslog
                port: 514
    opensearch:
      enabled: false
    mongodb:
      community:
        install: false
