apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mongodb-community-operator
  namespace: graylog
spec:
  interval: 5m
  targetNamespace: graylog
  releaseName: mongodb-community-operator
  chart:
    spec:
      chart: community-operator
      version: "0.13.0"
      sourceRef:
        kind: HelmRepository
        name: mongodb
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    database:
      name: mongodb-database
      namespace: graylog
    community-operator-crds:
      enabled: false
