apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: mongodb
  namespace: graylog
spec:
  members: 3
  type: ReplicaSet
  version: "7.0.25"
  security:
    authentication:
      modes: ["SCRAM"] # Standard password authentication
  users:
    - name: "graylog"
      db: graylog
      passwordSecretRef:
        name: mongodb-graylog-password
      roles:
        - name: readWrite
          db: graylog
        - name: clusterMonitor
          db: admin
      scramCredentialsSecretName: graylog
  additionalConnectionStringConfig:
    authSource: "graylog"
    connectTimeoutMS: "300000"
  statefulSet:
    spec:
      template:
        spec:
      volumeClaimTemplates:
        - metadata:
            name: data-volume
          spec:
            storageClassName: "ceph-block-3"
            resources:
              requests:
                storage: "2Gi"
        - metadata:
            name: logs-volume
          spec:
            resources:
              requests:
                storage: "1Gi"
            storageClassName: "ceph-block-3"
