apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: opensearch
  namespace: graylog
spec:
  interval: 5m
  targetNamespace: graylog
  releaseName: opensearch
  chart:
    spec:
      chart: opensearch
      version: "2.35.1"
      sourceRef:
        kind: HelmRepository
        name: opensearch
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    clusterName: "graylog"
    config:
      opensearch.yml: |-
        cluster.name: graylog
        network.host: 0.0.0.0
    extraEnvs:
    #  - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
    #    value: <strong_password>
      - name: plugins.security.ssl.http.enabled
        value: "false"
      - name: plugins.security.disabled
        value: "true"
    envFrom:
      - secretRef:
          name: graylog-opensearch-env
    opensearchJavaOpts: "-Xmx1024M -Xms1024M"
    resources:
      requests:
        cpu: "1000m"
        memory: "1536Mi"
      limits:
        cpu: "1000m"
        memory: "1536Mi"
    networkHost: "0.0.0.0"
    persistence:
      enabled: true
      enableInitChown: true
      storageClass: "ceph-block-3"
      size: 4Gi
