apiVersion: virt.virtink.smartx.com/v1alpha1
kind: VirtualMachine
metadata:
  name: ubuntu-container-rootfs
  namespace: virtink
spec:
  instance:
    cpu:
      coresPerSocket: 1
      sockets: 1
    disks:
    - name: ubuntu
    - name: cloud-init
    interfaces:
    - bridge: {}
      mac: 52:54:00:f3:e0:e9
      name: pod
    kernel:
      cmdline: console=ttyS0 root=/dev/vda rw
      image: smartxworks/virtink-kernel-5.15.12
    memory:
      size: 1Gi
  networks:
  - name: pod
    pod: {}
  resources: {}
  runPolicy: Once
  volumes:
  - containerRootfs:
      image: smartxworks/virtink-container-rootfs-ubuntu
      size: 4Gi
    name: ubuntu
  - cloudInit:
      userData: |-
        #cloud-config
        password: oogaecha2feiLaigaedeis
        chpasswd: { expire: False }
        ssh_pwauth: True
    name: cloud-init
