apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: stamp-bpf-reflector
  namespace: flux-system
spec:
  interval: 5m
  targetNamespace: stamp-bpf
  releaseName: stamp-bpf-reflector
  chart:
    spec:
      chart: stamp-bpf
      version: "0.1.13"
      sourceRef:
        kind: HelmRepository
        name: stamp-bpf
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    global:
      nodeSelector:
        stamp-role: "reflector"
      image:
        repository: registry.spbnix.com/stamp-bpf/stamp-bpf
        tag: f62c2c0
        pullPolicy: IfNotPresent
      tolerations:
        - operator: Exists
          effect: NoSchedule
    sender:
      enabled: false
    reflector:
      enabled: true
      interface: "ens33"
    
    hostNetwork: true
    dnsPolicy: ClusterFirstWithHostNet
    
    securityContext:
      privileged: true
      
    metrics:
      enabled: false
      port: 9374
      path: /metrics
      
    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi
        
    env:
      - name: GOMAXPROCS
        value: "1"
