repositories:
- name: cnpg
  url: https://cloudnative-pg.github.io/charts

releases:
- name: cloudnative-pg
  chart: cnpg/cloudnative-pg
  version: 0.24.0
  values:
  - ./values.yaml
  jsonPatches:
  - target:
      version: v1
      kind: CustomResourceDefinition
    patch:
    - op: add
      path: "/metadata/annotations/argocd.argoproj.io~1sync-options"
      value: "ServerSideApply=true"
